import path from "node:path";
import fs from "fs-extra";
import matter from "gray-matter";
import type { ContextPack } from "@ev-lite/shared";
import type { Registry } from "./registry.js";

const EVLITE_VERSION = "0.1.0";

function bulletList(items: readonly string[]): string {
  if (items.length === 0) return "_(none)_";
  return items.map((item) => `- ${item}`).join("\n");
}

export async function buildPack(
  pack: ContextPack,
  registry: Registry,
  root: string,
): Promise<string> {
  const sections: string[] = [];

  sections.push(
    [
      `# Context Pack — ${pack.goal}`,
      "",
      `> Generated by EvidenceVault Lite ${EVLITE_VERSION}`,
      `> Pack ID: ${pack.id}`,
      `> Generated at: ${new Date().toISOString()}`,
    ].join("\n"),
  );

  sections.push(["## Scope", "", pack.goal].join("\n"));
  sections.push(["## Output Goal", "", bulletList(pack.outputGoal)].join("\n"));
  sections.push(["## Do Not Infer", "", bulletList(pack.doNotInfer)].join("\n"));

  sections.push("---");

  const contextParts: string[] = ["## Context", ""];

  for (const evId of pack.mustRead) {
    const node = registry.nodes.find((n) => n.ev_id === evId);
    if (!node) {
      throw new Error(`Unresolved ev_id in mustRead: ${evId}`);
    }

    const absolutePath = path.join(root, node.path);
    const raw = await fs.readFile(absolutePath, "utf8");
    const { content } = matter(raw);
    const body = content.trim();
    const title = node.title ?? node.path;

    contextParts.push(`### ${title} (\`${node.path}\`)`);
    contextParts.push("");
    contextParts.push(body);
    contextParts.push("");
    contextParts.push("---");
    contextParts.push("");
  }

  sections.push(contextParts.join("\n").trimEnd());

  return sections.join("\n\n") + "\n";
}
