import path from "node:path";
import fs from "fs-extra";
import fg from "fast-glob";

const SNAPSHOT_VERSION = "0.1.0";

const DEFAULT_INCLUDE: string[] = [
  "**/*.ts",
  "**/*.tsx",
  "**/*.js",
  "**/*.jsx",
  "**/*.mjs",
  "**/*.cjs",
  "**/*.yaml",
  "**/*.yml",
  "**/package.json",
];

const DEFAULT_EXCLUDE: string[] = [
  "**/node_modules/**",
  "**/dist/**",
  "**/.git/**",
  "**/.ev-lite/**",
  "**/*.test.ts",
  "**/*.spec.ts",
  "**/*.test.tsx",
  "**/*.spec.tsx",
  "**/*.d.ts",
  "**/*.tsbuildinfo",
];

const EXT_TO_LANGUAGE: Record<string, string> = {
  ts: "ts",
  tsx: "tsx",
  js: "js",
  jsx: "jsx",
  mjs: "js",
  cjs: "js",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  md: "md",
  css: "css",
  scss: "scss",
  html: "html",
  sh: "sh",
};

export type SnapshotOptions = {
  path: string;
  root: string;
  output?: string;
  stack?: string;
  title?: string;
  include?: string[];
  exclude?: string[];
  noContent?: boolean;
};

export type SnapshotMeta = {
  evId: string;
  output: string;
  fileCount: number;
};

function toPosix(p: string): string {
  return p.replace(/\\/g, "/");
}

function detectLanguage(filePath: string): string {
  const ext = path.extname(filePath).slice(1).toLowerCase();
  return EXT_TO_LANGUAGE[ext] ?? ext ?? "text";
}

function getFenceLength(content: string): number {
  const matches = content.match(/`+/g);
  if (!matches) return 3;
  const maxRun = matches.reduce((m, s) => Math.max(m, s.length), 0);
  return Math.max(3, maxRun + 1);
}

type TreeNode = {
  name: string;
  children: Map<string, TreeNode>;
  isFile: boolean;
};

function buildTreeStructure(paths: string[]): TreeNode {
  const root: TreeNode = { name: "", children: new Map(), isFile: false };
  for (const p of paths) {
    const parts = p.split("/").filter(Boolean);
    let current = root;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      let child = current.children.get(part);
      if (!child) {
        child = { name: part, children: new Map(), isFile: isLast };
        current.children.set(part, child);
      }
      current = child;
    }
  }
  return root;
}

function renderTreeNode(node: TreeNode, indent: number): string[] {
  const lines: string[] = [];
  const entries = [...node.children.values()].sort((a, b) => {
    if (a.isFile !== b.isFile) return a.isFile ? 1 : -1;
    return a.name.localeCompare(b.name);
  });
  for (const child of entries) {
    const prefix = "  ".repeat(indent);
    const suffix = child.isFile ? "" : "/";
    lines.push(`${prefix}${child.name}${suffix}`);
    if (!child.isFile) {
      lines.push(...renderTreeNode(child, indent + 1));
    }
  }
  return lines;
}

function renderTree(paths: string[]): string {
  const root = buildTreeStructure(paths);
  return renderTreeNode(root, 0).join("\n");
}

type ResolvedContext = {
  absolutePath: string;
  basename: string;
  stack: string;
  evId: string;
  sourcePath: string;
  title: string;
  output: string;
  include: string[];
  exclude: string[];
};

function resolveContext(options: SnapshotOptions): ResolvedContext {
  const absolutePath = path.isAbsolute(options.path)
    ? options.path
    : path.resolve(options.root, options.path);
  const basename = path.basename(absolutePath);
  const stack = options.stack ?? basename;
  const evId = `ev:${stack}.snapshot-${stack}-${basename}`;
  const sourcePath = toPosix(path.relative(options.root, absolutePath)) || ".";
  const title = options.title ?? `Directory: ${sourcePath}`;
  const output =
    options.output ??
    path.join(
      options.root,
      ".ev-lite",
      "snapshots",
      `${stack}-${basename}.md`,
    );
  const include = options.include?.length ? options.include : DEFAULT_INCLUDE;
  const exclude = [...DEFAULT_EXCLUDE, ...(options.exclude ?? [])];

  return {
    absolutePath,
    basename,
    stack,
    evId,
    sourcePath,
    title,
    output,
    include,
    exclude,
  };
}

async function scanFiles(
  cwd: string,
  include: string[],
  exclude: string[],
): Promise<string[]> {
  const files = await fg(include, {
    cwd,
    ignore: exclude,
    onlyFiles: true,
    dot: false,
  });
  return files.sort();
}

function buildFrontmatter(evId: string, stack: string): string {
  return [
    "---",
    `ev_id: ${evId}`,
    `stack: ${stack}`,
    "status: active",
    "tags: [snapshot, code]",
    "depends_on: []",
    "related: []",
    "supersedes: []",
    "---",
  ].join("\n");
}

function buildHeader(title: string, sourcePath: string): string {
  return [
    `# ${title}`,
    "",
    `> Generated by EvidenceVault Lite ${SNAPSHOT_VERSION}`,
    `> Source: ${sourcePath}`,
    `> Generated at: ${new Date().toISOString()}`,
  ].join("\n");
}

function buildTreeSection(tree: string): string {
  return ["## Tree", "", "```", tree || "(empty)", "```"].join("\n");
}

function buildFileSection(filePath: string, content: string): string {
  const language = detectLanguage(filePath);
  const fence = "`".repeat(getFenceLength(content));
  const trimmedContent = content.replace(/\n+$/, "");
  return [
    `## ${filePath}`,
    "",
    `${fence}${language}`,
    trimmedContent,
    fence,
  ].join("\n");
}

async function assembleSnapshot(ctx: ResolvedContext, noContent: boolean): Promise<{
  markdown: string;
  files: string[];
}> {
  if (!(await fs.pathExists(ctx.absolutePath))) {
    throw new Error(`Path not found: ${ctx.sourcePath}`);
  }
  const stat = await fs.stat(ctx.absolutePath);
  if (!stat.isDirectory()) {
    throw new Error(`Path is not a directory: ${ctx.sourcePath}`);
  }

  const files = await scanFiles(ctx.absolutePath, ctx.include, ctx.exclude);
  const tree = renderTree(files);

  const sections: string[] = [
    buildFrontmatter(ctx.evId, ctx.stack),
    buildHeader(ctx.title, ctx.sourcePath),
    buildTreeSection(tree),
    "---",
  ];

  if (!noContent) {
    for (const filePath of files) {
      const absoluteFilePath = path.join(ctx.absolutePath, filePath);
      const content = await fs.readFile(absoluteFilePath, "utf8");
      sections.push(buildFileSection(filePath, content));
      sections.push("---");
    }
  }

  return {
    markdown: sections.join("\n\n") + "\n",
    files,
  };
}

export async function buildSnapshot(options: SnapshotOptions): Promise<string> {
  const ctx = resolveContext(options);
  const result = await assembleSnapshot(ctx, options.noContent ?? false);
  return result.markdown;
}

export async function generateSnapshot(
  options: SnapshotOptions,
): Promise<SnapshotMeta> {
  const ctx = resolveContext(options);
  const result = await assembleSnapshot(ctx, options.noContent ?? false);

  await fs.ensureDir(path.dirname(ctx.output));
  await fs.writeFile(ctx.output, result.markdown, "utf8");

  return {
    evId: ctx.evId,
    output: ctx.output,
    fileCount: result.files.length,
  };
}
