export function buildHandoverTemplate(
  name: string,
  createdAt: string,
): string {
  const evId = `ev:handover.${name}`;
  return [
    "---",
    `ev_id: ${evId}`,
    `type: handover`,
    `title: ${name}`,
    `status: active`,
    `created_at: ${createdAt}`,
    ``,
    `must_read: []`,
    `optional_read: []`,
    ``,
    `goal: ""`,
    `current_state: ""`,
    `next_actions: []`,
    ``,
    `active_decisions: []`,
    `unresolved_questions: []`,
    `known_risks: []`,
    ``,
    `related_packs: []`,
    `related_docs: []`,
    ``,
    `supersedes: []`,
    `superseded_by: []`,
    ``,
    `tags: []`,
    "---",
    "",
    `# ${name}`,
    "",
    `<!-- goal, current_state, next_actions を記述 -->`,
    "",
  ].join("\n");
}
